<li class="nav-item">
    <a class="nav-link {{request()->routeIs('admin.index')? 'active':''}}"
       href="{{ route('index') }}">Главная</a></li>
<li class="nav-item">
    <a class="nav-link {{request()->routeIs('admin.addNews')? 'active':''}}"
       href="{{ route('admin.news.create') }}">Добавить новость</a></li>
<li class="nav-item">
    <a class="nav-link {{request()->routeIs('admin.index')? 'active':''}}"
       href="{{ route('admin.news.index') }}">Работа с новостями</a></li>
<li class="nav-item">
    <a class="nav-link {{request()->routeIs('admin.index')? 'active':''}}"
       href="{{ route('admin.category.index') }}">Работа с категориями</a></li>
<li class="nav-item">
    <a class="nav-link {{request()->routeIs('admin.addCategory')? 'active':''}}"
       href="{{ route('admin.category.create') }}">Добавить категорию</a></li>
<li class="nav-item">
    <a class="nav-link {{request()->routeIs('admin.index')? 'active':''}}"
       href="{{ route('admin.updateProfile') }}">Редактировать профиль</a></li>
<li class="nav-item">
    <a class="nav-link {{request()->routeIs('admin.index')? 'active':''}}"
       href="{{ route('admin.user.index') }}">Работа с профилями</a></li>
